// <auto-generated />
using FirstEntityProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FirstEntityProject.Data.Migrations
{
    [DbContext(typeof(PatikaFirstDbContex))]
    [Migration("20241218091615_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FirstEntityProject.GameData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Games", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "The Witcher 3: Wild Hunt",
                            Platform = "PC",
                            Rating = 0m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Red Dead Redemption 2",
                            Platform = "PlayStation",
                            Rating = 0m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Halo Infinite",
                            Platform = "Xbox",
                            Rating = 0m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Super Mario Odyssey",
                            Platform = "Nintendo Switch",
                            Rating = 0m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cyberpunk 2077",
                            Platform = "PC",
                            Rating = 0m
                        });
                });

            modelBuilder.Entity("FirstEntityProject.MovieData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Science Fiction",
                            ReleaseYear = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Crime",
                            ReleaseYear = 1972,
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Action",
                            ReleaseYear = 2008,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Crime",
                            ReleaseYear = 1994,
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Drama",
                            ReleaseYear = 1994,
                            Title = "Forrest Gump"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
